#!/bin/bash

# Get the Python script file name from the environment variable
PYFILE="$PYFILE"

# Check if the PYFILE variable is set
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi

# Run the Python script
python3 "$PYFILE"
